import './ai-hub.css';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const STORE_KEY='smai_ai_hub_history_v1';
const COMMANDS=[['deepsearch','מחקר מעמיק עם מקורות'],['image','יצירת תמונה'],['summarize','סיכום ברור וקצר'],['translate','תרגום לשפה שאבחר'],['rewrite','שכתוב בסגנון אחר'],['compare','השוואה בין אפשרויות'],['plan','בניית תוכנית פעולה'],['facts','בדיקת עובדות ומקורות'],['safety','בדיקת סיכון והצעד הבטוח'],['report','ניסוח דיווח מסודר לצוות'],['story','יצירת סיפור אינטראקטיבי'],['email','כתיבת מייל'],['brainstorm','סיעור מוחות ורעיונות'],['explain','הסבר פשוט או מעמיק'],['checklist','יצירת רשימת משימות'],['timeline','בניית ציר זמן'],['decision','עזרה בקבלת החלטה'],['practice','תרגול שיחה או תגובה'],['quiz','יצירת שאלון'],['source','פתיחת וניתוח קישור ציבורי']];

export function renderAiHub(app,{request,user}){
  let history=[];try{history=JSON.parse(localStorage.getItem(STORE_KEY)||'[]').slice(-30);}catch{}
  app.innerHTML=`<section class="ai-hub">
    <aside class="ai-hub-rail">
      <div class="ai-hub-brand"><img src="/assets/smai-ai-assistant.png" alt=""><div><b>SMAI AI</b><small>מרכז הבטיחות החכם</small></div></div>
      <button class="ai-new-chat" type="button">＋ שיחה חדשה</button>
      <nav aria-label="פעולות AI">
        <button data-seed="עזור לי להבין מה הצעד הבטוח הבא במקרה שלי">בדיקת מצב בטוחה</button>
        <button data-seed="עזור לי לנסח דיווח ברור ומסודר לצוות">ניסוח דיווח</button>
        <button data-seed="הסבר לי איך לשמור ראיות דיגיטליות בצורה בטוחה">שמירת ראיות</button>
        <button data-seed="חפש באינטרנט מידע עדכני ומקורות אמינים בנושא הבא: ">מחקר ברשת</button>
      </nav>
      <p>המערכת מספקת מידע כללי בלבד. בסכנה מיידית מתקשרים ל־100.</p>
    </aside>
    <main class="ai-hub-main">
      <header class="ai-hub-head"><div><span class="ai-live-dot"></span><b>SMAI Intelligence</b><small>שיחה, קול, חיפוש וכלים אינטראקטיביים</small></div><div class="ai-hub-toggles"><label><input id="aiAgent" type="checkbox" checked> מצב סוכן</label><label><input id="aiWeb" type="checkbox"> חיפוש ברשת</label><label><input id="aiVoice" type="checkbox"> הקראת תשובות</label>${user?'<label><input id="aiCloud" type="checkbox"> גיבוי בענן</label>':''}</div></header>
      <div class="ai-hub-thread" id="aiHubThread" aria-live="polite"></div>
      <div class="ai-hub-starters" id="aiHubStarters"><button data-seed="מישהו מטריד אותי ברשת, מה לעשות?">מטרידים אותי</button><button data-seed="פרצו לי לחשבון. תן לי צעדים מיידיים">פרצו לי לחשבון</button><button data-seed="עזור לי לבדוק אם הודעה שקיבלתי היא הונאה">בדיקת הונאה</button><button data-seed="אני צריך עזרה עכשיו">אני צריך עזרה</button></div>
      <div class="ai-command-menu" id="aiCommandMenu" hidden></div><form class="ai-hub-composer" id="aiHubForm"><button type="button" id="aiHubMic" aria-label="דיבור למערכת">◉</button><textarea id="aiHubInput" rows="1" maxlength="12000" placeholder="שאלו כל דבר או הקלידו @ לפקודות…" required></textarea><button type="submit" class="ai-hub-send" aria-label="שליחה">➤</button><div class="ai-hub-meta"><span>Enter לשליחה · @ לפקודות</span><span>אל תשתפו סיסמאות או קודי אימות</span></div></form>
    </main>
  </section>`;
  const thread=app.querySelector('#aiHubThread'),form=app.querySelector('#aiHubForm'),input=app.querySelector('#aiHubInput'),send=form.querySelector('.ai-hub-send'),starters=app.querySelector('#aiHubStarters');
  let cloudTimer=null;const persist=()=>{localStorage.setItem(STORE_KEY,JSON.stringify(history.slice(-30)));if(user&&app.querySelector('#aiCloud')?.checked){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>request('/api/ai/history','PUT',{history:history.slice(-30)}).catch(()=>{}),700);}};
  const scroll=()=>requestAnimationFrame(()=>thread.scrollTop=thread.scrollHeight);
  const actions=result=>{const links=[];if(result?.reportSuggestion)links.push([result.reportSuggestion.href,'פתיחת דיווח','primary']);links.push(['/report','דיווח לצוות'],['/articles','מדריכים'],['/my','הפניות שלי']);return `<div class="ai-hub-actions">${links.map(([href,label,kind])=>`<a href="${escapeHtml(href)}" class="${kind||''}">${escapeHtml(label)}</a>`).join('')}</div>`;};
  const controls=result=>result.controls?.length?`<div class="ai-adaptive-controls">${result.controls.map(group=>`<section><b>${escapeHtml(group.label)}</b><div>${group.options.map(option=>`<button type="button" data-ai-choice="${escapeHtml(group.label+': '+option)}">${escapeHtml(option)}</button>`).join('')}</div></section>`).join('')}</div>`:'';
  const add=(role,text,result={})=>{const article=document.createElement('article');article.className='ai-hub-message '+role;article.innerHTML=role==='model'?`<img src="/assets/smai-ai-assistant.png" alt=""><div>${result.openedPage?`<a class="ai-browser-card" href="${escapeHtml(result.openedPage.url)}" target="_blank" rel="noopener noreferrer"><span class="ai-browser-bar"><i></i><i></i><i></i><b>${escapeHtml(result.openedPage.host)}</b></span><strong>${escapeHtml(result.openedPage.title)}</strong><small>${escapeHtml(result.openedPage.description||'עמוד ציבורי שנקרא על ידי הסוכן')}</small></a>`:''}<div class="ai-hub-answer">${escapeHtml(text).replace(/\n/g,'<br>')}</div>${result.sources?.length?`<div class="ai-hub-sources"><b>מקורות</b>${result.sources.map(source=>`<a href="${escapeHtml(source.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(source.title||source.url)}</a>`).join('')}</div>`:''}${controls(result)}${actions(result)}</div>`:`<div>${escapeHtml(text)}</div>`;thread.append(article);article.querySelectorAll('[data-ai-choice]').forEach(button=>button.onclick=()=>{input.value=[input.value.trim(),button.dataset.aiChoice].filter(Boolean).join(' · ');input.focus();input.dispatchEvent(new Event('input'));});scroll();};
  if(history.length)history.forEach(item=>add(item.role,item.text,item.result||{}));else add('model','היי, אני מרכז ה־AI של SMAI Sentinel. אפשר לדבר איתי בחופשיות, לבקש מחקר עם מקורות, לקבל צעדים בטוחים או לפתוח דיווח מסודר.');
  const typing=()=>{const node=document.createElement('article');node.className='ai-hub-message model typing';node.innerHTML='<img src="/assets/smai-ai-assistant.png" alt=""><div><i></i><i></i><i></i><span>חושב ומארגן תשובה…</span></div>';thread.append(node);scroll();return node;};
  const progress=(kind,label)=>{const node=document.createElement('article');node.className=`ai-task-card ${kind}`;node.innerHTML=`<div class="ai-task-visual"><span></span><b>${kind==='image'?'IMAGE':'DEEP'}</b></div><div><strong>${escapeHtml(label)}</strong><p>מתחיל…</p><div class="ai-task-track"><i></i></div><small>0% · מחשב זמן…</small></div>`;thread.append(node);scroll();let value=0;const timer=setInterval(()=>{value=Math.min(92,value+Math.max(2,Math.round((95-value)/8)));node.querySelector('.ai-task-track i').style.width=value+'%';node.querySelector('small').textContent=`${value}% · בערך ${Math.max(2,Math.ceil((100-value)/4))} שניות`;node.querySelector('p').textContent=value<30?'מכין את המשימה…':value<65?'מעבד ומצליב מידע…':'מסיים ומארגן תוצאה…';},650);return {node,done(){clearInterval(timer);node.querySelector('.ai-task-track i').style.width='100%';node.querySelector('small').textContent='100% · הושלם';},fail(){clearInterval(timer);node.classList.add('failed');node.querySelector('p').textContent='המשימה לא הושלמה';}};};
  const submit=async()=>{let prompt=input.value.trim();if(!prompt||send.disabled)return;const imageMode=/^@image\b/i.test(prompt),deepMode=/^@deepsearch\b/i.test(prompt);prompt=prompt.replace(/^@(image|deepsearch)\s*/i,'').trim()||prompt;input.value='';input.style.height='auto';starters?.remove();add('user',(imageMode?'@image ':deepMode?'@deepsearch ':'')+prompt);history.push({role:'user',text:prompt,createdAt:new Date().toISOString()});persist();send.disabled=true;const task=imageMode?progress('image','יוצר תמונה'):deepMode?progress('deep','מבצע מחקר מעמיק'):null,pending=task?null:typing();try{if(imageMode){const result=await request('/api/ai/image','POST',{prompt});task.done();const card=document.createElement('article');card.className='ai-image-result';card.innerHTML=`<img src="${escapeHtml(result.image)}" alt="${escapeHtml(prompt)}"><div><b>התמונה מוכנה</b><a href="${escapeHtml(result.image)}" download="smai-ai-image.jpg">הורדה</a></div>`;thread.append(card);scroll();history.push({role:'model',text:'נוצרה תמונה: '+prompt,createdAt:new Date().toISOString()});persist();return;}const result=await request('/api/ai','POST',{prompt,history:history.slice(-12),consent:true,requireModel:true,agent:app.querySelector('#aiAgent').checked,webSearch:deepMode||app.querySelector('#aiWeb').checked});pending?.remove();task?.done();add('model',result.text,result);history.push({role:'model',text:result.text,createdAt:new Date().toISOString(),result:{sources:result.sources||[],openedPage:result.openedPage||null,controls:result.controls||[],reportSuggestion:result.reportSuggestion||null}});persist();if(app.querySelector('#aiVoice').checked&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(result.text.slice(0,1800)));}}catch(error){pending?.remove();task?.fail();add('model',error.message||'לא הצלחתי להשיב כרגע. נסו שוב בעוד רגע.');}finally{send.disabled=false;input.focus();}};
  const commandMenu=app.querySelector('#aiCommandMenu');const drawCommands=()=>{const match=input.value.match(/^@([a-z]*)$/i);if(!match){commandMenu.hidden=true;return;}const query=match[1].toLowerCase(),items=COMMANDS.filter(([name,label])=>name.startsWith(query)||label.includes(query)).slice(0,10);commandMenu.innerHTML=items.map(([name,label])=>`<button type="button" data-command="${name}"><b>@${name}</b><span>${label}</span></button>`).join('');commandMenu.hidden=!items.length;commandMenu.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>{input.value='@'+button.dataset.command+' ';commandMenu.hidden=true;input.focus();});};
  form.onsubmit=event=>{event.preventDefault();submit();};input.onkeydown=event=>{if(event.key==='Escape')commandMenu.hidden=true;if(event.key==='Enter'&&!event.shiftKey&&!(!commandMenu.hidden&&input.value.match(/^@[a-z]*$/i))){event.preventDefault();submit();}};input.oninput=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,180)+'px';drawCommands();};
  app.querySelectorAll('[data-seed]').forEach(button=>button.onclick=()=>{input.value=button.dataset.seed;input.focus();input.dispatchEvent(new Event('input'));});
  app.querySelector('.ai-new-chat').onclick=()=>{history=[];persist();thread.innerHTML='';add('model','נפתחה שיחה חדשה. במה תרצו שאעזור?');};
  const cloud=app.querySelector('#aiCloud');if(cloud){cloud.checked=localStorage.getItem('smai_ai_cloud')==='1';cloud.onchange=async()=>{localStorage.setItem('smai_ai_cloud',cloud.checked?'1':'0');if(cloud.checked){try{const saved=await request('/api/ai/history');if(saved.history?.length){history=saved.history;localStorage.setItem(STORE_KEY,JSON.stringify(history));thread.innerHTML='';history.forEach(item=>add(item.role,item.text,item.result||{}));}else persist();}catch{cloud.checked=false;localStorage.setItem('smai_ai_cloud','0');}}};if(cloud.checked)cloud.dispatchEvent(new Event('change'));}
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition,mic=app.querySelector('#aiHubMic');if(!Recognition)mic.hidden=true;else{const recognition=new Recognition();recognition.lang=document.documentElement.lang==='en'?'en-US':'he-IL';recognition.interimResults=true;recognition.continuous=false;let overlay=null;const closeVoice=()=>{overlay?.classList.add('closing');setTimeout(()=>overlay?.remove(),180);overlay=null;mic.classList.remove('listening');};recognition.onstart=()=>{mic.classList.add('listening');overlay=document.createElement('div');overlay.className='ai-voice-overlay';overlay.innerHTML='<div class="ai-voice-bubble"><span class="ai-voice-orbit"></span><div class="ai-voice-wave"><i></i><i></i><i></i><i></i><i></i></div><strong>אני מקשיב</strong><p>דברו עכשיו — התמלול יופיע כאן</p><div class="ai-voice-live">…</div><button type="button">סיום</button></div>';document.body.append(overlay);overlay.querySelector('button').onclick=()=>recognition.stop();};recognition.onend=closeVoice;recognition.onerror=closeVoice;recognition.onresult=event=>{const transcript=[...event.results].map(result=>result[0].transcript).join(' ');input.value=transcript;overlay?.querySelector('.ai-voice-live')?.replaceChildren(document.createTextNode(transcript||'…'));input.dispatchEvent(new Event('input'));};mic.onclick=()=>{try{recognition.start();}catch{}};}
}
