import {request} from './api.js';
import './assistant.css';
import './assistant-voice.css';

export function initAssistant(){
  const toggle=document.createElement('button');toggle.id='ai-fab';toggle.className='btn btn-p';toggle.setAttribute('aria-label','פתיחת עוזר בטיחות');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<span aria-hidden="true">✦</span> עוזר SMAI';
  const dialog=document.createElement('dialog');dialog.className='sentinel-assistant';
  dialog.innerHTML=`<header><div class="assistant-brand"><span class="assistant-orb" aria-hidden="true"></span><div><strong>SMAI AI</strong><p>שיחה חכמה · קול וטקסט</p></div></div><div class="assistant-header-actions"><button type="button" class="assistant-sound iconbtn" aria-label="הקראת תשובות" aria-pressed="true">◖))</button><button type="button" class="iconbtn assistant-close" aria-label="סגירה">✕</button></div></header><div class="assistant-notice">העוזר מספק מידע כללי בלבד ואינו תחליף לאיש מקצוע או לשירות חירום. בסכנה מיידית חייגו 100; לתמיכה נפשית בישראל ער״ן 1201.</div><div class="assistant-messages" aria-live="polite"><div class="assistant-message model assistant-welcome"><span class="assistant-avatar" aria-hidden="true">✦</span><div><strong>היי, אני עוזר הבטיחות של SMAI.</strong><p>אפשר לכתוב או לדבר איתי. אקשיב, אענה ואעזור לבחור את הצעד הבטוח הבא.</p></div></div><div class="assistant-suggestions"><button type="button">פרצו לי לחשבון</button><button type="button">מישהו מטריד אותי</button><button type="button">איך שומרים ראיות?</button></div></div><form><label class="sr-only" for="assistant-input">הודעה לעוזר</label><div class="assistant-voice-state" hidden><span></span><b>מקשיב…</b><small>דברו עכשיו, הטקסט יופיע כאן</small></div><div class="assistant-composer"><button class="assistant-mic" type="button" aria-label="התחלת שיחה קולית" aria-pressed="false"><span></span></button><textarea id="assistant-input" rows="1" maxlength="6000" required placeholder="כתבו או דברו…" aria-describedby="assistant-hint"></textarea><button class="assistant-send" type="submit" aria-label="שליחת הודעה">➤</button></div><div class="assistant-form-meta"><span id="assistant-hint">Enter לשליחה · לחצו על הבועה כדי לדבר</span><span>מענה AI · אל תשתפו סודות</span></div><p class="assistant-error" role="alert"></p></form>`;
  document.body.append(toggle,dialog);
  const close=dialog.querySelector('.assistant-close'),messages=dialog.querySelector('.assistant-messages'),input=dialog.querySelector('textarea'),form=dialog.querySelector('form'),error=dialog.querySelector('[role=alert]'),button=form.querySelector('.assistant-send'),mic=form.querySelector('.assistant-mic'),voiceState=form.querySelector('.assistant-voice-state'),sound=dialog.querySelector('.assistant-sound');
  toggle.onclick=()=>{dialog.showModal();toggle.setAttribute('aria-expanded','true');setTimeout(()=>input.focus(),80);};close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{toggle.setAttribute('aria-expanded','false');window.speechSynthesis?.cancel();toggle.focus();});
  const history=[],scroll=()=>{messages.scrollTop=messages.scrollHeight;};
  let speakReplies=true,listening=false,recognition=null,dictated=false;
  sound.onclick=()=>{speakReplies=!speakReplies;sound.setAttribute('aria-pressed',String(speakReplies));sound.classList.toggle('off',!speakReplies);if(!speakReplies)window.speechSynthesis?.cancel();};
  const speak=text=>{if(!speakReplies||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=/[א-ת]/.test(text)?'he-IL':'en-US';utterance.rate=.98;window.speechSynthesis.speak(utterance);};
  const add=(text,kind)=>{const row=document.createElement('div');row.className='assistant-message '+kind;const bubble=document.createElement('div');bubble.textContent=text;if(kind==='model'){const avatar=document.createElement('span');avatar.className='assistant-avatar';avatar.setAttribute('aria-hidden','true');avatar.textContent='✦';row.append(avatar);}row.append(bubble);messages.append(row);scroll();};
  const typing=()=>{const row=document.createElement('div');row.className='assistant-message model assistant-typing';row.setAttribute('aria-label','מערכת ה-AI חושבת');row.innerHTML='<span class="assistant-avatar" aria-hidden="true">✦</span><div><i></i><i></i><i></i><small>חושב…</small></div>';messages.append(row);scroll();return row;};
  const resize=()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,132)+'px';};input.addEventListener('input',()=>{dictated=false;resize();});input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();form.requestSubmit();}});
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  if(Recognition){recognition=new Recognition();recognition.lang=document.documentElement.lang==='en'?'en-US':'he-IL';recognition.interimResults=true;recognition.continuous=false;let base='';recognition.onstart=()=>{listening=true;dictated=true;base=input.value.trim();mic.classList.add('listening');mic.setAttribute('aria-pressed','true');voiceState.hidden=false;};recognition.onresult=event=>{let final='',interim='';for(let i=event.resultIndex;i<event.results.length;i++){const text=event.results[i][0].transcript;if(event.results[i].isFinal)final+=text;else interim+=text;}input.value=[base,final||interim].filter(Boolean).join(' ');resize();};recognition.onerror=event=>{if(event.error!=='aborted')error.textContent='לא הצלחתי לשמוע. בדקו הרשאת מיקרופון ונסו שוב.';};recognition.onend=()=>{listening=false;mic.classList.remove('listening');mic.setAttribute('aria-pressed','false');voiceState.hidden=true;input.focus();};mic.onclick=()=>{error.textContent='';if(listening)recognition.stop();else recognition.start();};}else{mic.hidden=true;dialog.querySelector('#assistant-hint').textContent='Enter לשליחה · הדפדפן הזה אינו תומך בתמלול קולי';}
  dialog.querySelectorAll('.assistant-suggestions button').forEach(chip=>chip.onclick=()=>{input.value=chip.textContent;resize();form.requestSubmit();dialog.querySelector('.assistant-suggestions')?.remove();});
  form.onsubmit=async event=>{
    event.preventDefault();if(!input.value.trim()||button.disabled)return;
    const prompt=input.value.trim(),voiceRequest=dictated;dictated=false;button.disabled=true;error.textContent='';add(prompt,'user');input.value='';resize();dialog.querySelector('.assistant-suggestions')?.remove();const indicator=typing();
    try{
      const result=await request('/api/ai','POST',{prompt,history:history.slice(-10),consent:true,requireModel:true});
      if(!['gemini','workers-ai'].includes(result.mode))throw new Error('שירות ה-AI עדיין לא מחובר.');
      if(result.safetyRisk){const alert=document.createElement('div');alert.className='assistant-safety';const strong=document.createElement('strong');strong.textContent='לא נשארים עם זה לבד';const text=document.createElement('span');text.textContent=result.safetyEscalated?'התראה דחופה הועברה לצוות SMAI לבדיקה. אין להמתין למענה מהאתר אם קיימת סכנה.':'לא ניתן להעביר התראה לצוות ללא חשבון מחובר.';const links=document.createElement('div');links.innerHTML='<a href="tel:100">משטרה 100</a><a href="tel:1201">ער״ן 1201</a>';alert.append(strong,text,links);messages.append(alert);}
      if(result.reportSuggestion){const card=document.createElement('div');card.className='assistant-action-card';const title=document.createElement('strong');title.textContent=result.reportSuggestion.label;const copy=document.createElement('span');copy.textContent=result.incident?.urgent?'אם קיימת סכנה עכשיו, אין להמתין לתשובה באתר. עברו למקום בטוח ופנו לשירות החירום המתאים.':'אפשר לפתוח דיווח מסודר ולצרף פרטים בקצב שנוח לכם.';const actions=document.createElement('div');const report=document.createElement('a');report.href=result.reportSuggestion.href;report.textContent='פתיחת דיווח';report.className='assistant-action-primary';actions.append(report);for(const number of result.incident?.resources||[]){const link=document.createElement('a');link.href=`tel:${number}`;link.textContent=number==='118'?'רווחה 118':number==='105'?'מוקד 105':`חירום ${number}`;actions.append(link);}card.append(title,copy,actions);messages.append(card);}
      add(result.text,'model');if(voiceRequest)speak(result.text);history.push({role:'user',text:prompt},{role:'model',text:result.text});history.splice(0,Math.max(0,history.length-10));
    }catch(e){error.textContent=e.message;input.value=prompt;resize();}
    finally{indicator.remove();button.disabled=false;input.focus();scroll();}
  };
}
